### ISSUE TITLE
ModuleNotFoundError: No module named 'cocotb.drivers'

### ISSUE THREAD

**Issue by Bellamarigo** [cocotb/cocotb-bus#53]
i have tried to un install and reinstall cocotb bus ,still gives me the same error 
ModuleNotFoundError: No module named 'cocotb.drivers'
AttributeError: 'NoneType' object has no attribute 'log'
     0.00ns ERROR    gpi                                Passing event to upper layer failed
VCD info: dumpfile dump.vcd opened for output.
ERROR: results.xml was not written by the simulation!

when i try to re install cocotb bus
i get this error
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: cocotb[bus] in ./.local/lib/python3.10/site-packages (1.7.2)
Requirement already satisfied: find-libpython in ./.local/lib/python3.10/site-packages (from cocotb[bus]) (0.3.0)
Requirement already satisfied: cocotb-bus in ./.local/lib/python3.10/site-packages (from cocotb[bus]) (0.2.1)

**Comment by cmarqu** [comment]
You likely need `cocotb_bus.drivers`, not `cocotb.drivers`.

**Comment by Bellamarigo** [comment]
thanks
