### ISSUE TITLE
_AssignmentResult has been removed from cocotb main branch

### ISSUE THREAD

**Issue by davekeeshan** [cocotb/cocotb-bus#70]
`_AssignmentResult` was remove from the main branch of cocotb:

[remove deprecated handle <= syntax ](https://github.com/cocotb/cocotb/commit/f0b2b906ff12ecdc6da5f0445e3f5a3f136bc106)

it is used in `bus.py` in the `_le_` overload cases, unsure why that was done here, I am assuming it was an upstream problem in cocotb and can be wholly removed

**Comment by davekeeshan** [comment]
I see this has been brought up in #64

**Comment by alexforencich** [comment]
Is there going to be a new cocotb-bus release at some point with this fix included?  Right now the current release of cocotb-bus does not work with the current release of cocotb....
